export const searchRatingEndPoint = 'https://api.ageofempires.com/api/v2/AgeII/GetMPFull';
export const getMatchListEndPoint = 'https://api.ageofempires.com/api/v2/AgeII/GetMPMatchList';
export const getPlayerListEndPoint = 'https://api.ageofempires.com/api/v2/AgeII/GetMPMatchDetail';
export const civilizations: Record<string, string> = {
	Aztecs: '阿茲特克',
	Britons: '不列顛',
	Byzantines: '拜占庭',
	Celts: '塞爾特',
	Chinese: '中國',
	Franks: '法蘭克',
	Goths: '哥德',
	Huns: '匈人',
	Japanese: '日本',
	Koreans: '韓國',
	Malay: '馬來',
	Mongols: '蒙古',
	Persians: '波斯',
	Saracens: '薩拉森',
	Spanish: '西班牙',
	Teutons: '條頓',
	Turks: '土耳其',
	Vikings: '維京',
	Berbers: '柏柏',
	Cumans: '庫曼人',
	Italians: '義大利',
	Magyars: '馬札爾',
	Portuguese: '葡萄牙',
	Slavs: '斯拉夫',
	Bulgarians: '保加利亞',
	Dravidians: '達羅毗荼',
	Khmer: '高棉',
	Malians: '馬利',
	Tatars: '韃靼',
	Ethiopians: '衣索比亞',
	Incas: '印加',
	Burmese: '緬甸',
	Vietnamese: '越南',
	Sicilians: '西西里',
	Bohemians: '波希米亞',
	Poles: '波蘭',
	Bengalis: '孟加拉',
	Gurjaras: '瞿哲羅',
	Hindustanis: '印度斯坦',
	Romans: '羅馬',
};
export const mapTypes: Record<string, string> = {
	Arabia: '阿拉伯',
	Arena: '競技場',
	Baltic: '波羅的海',
	'Black Forest': '黑森林',
	Coastal: '海岸',
	Continental: '大陸',
	'Crater Lake': '火山口湖',
	Fortress: '堡壘',
	'Gold Rush': '淘金',
	Highland: '高地',
	Islands: '島嶼',
	Mediterranean: '地中海',
	Migration: '遷徙',
	Rivers: '河流',
	'Team Islands': '雙島',
	Yucatan: '猶加敦',
	Nomad: '遊牧',
	Iberia: '伊比利亞',
	Britain: '不列顛',
	Mideast: '中東',
	Texas: '德州',
	Italy: '義大利',
	'Central America': '中美洲',
	France: '法國',
	'Norse Lands': '北歐',
	'Sea of Japan': '日本海',
	Byzantium: '拜占庭',
	Custom: '自訂',
	Hideout: '藏身之處',
};
